version: "2"

networks:  
  nginx-net:
services:
 web_server:
  build: .
  ports:
    - "443:443"
    - "80:80"
    - "22:22"
 git-serve:
  image: gitea/gitea:latest
  restart: always
  networks:
   - nginx-net
  volumes:
   - ./gitea:/data
   #- ./admin:/admin
  ports:
   - "4443:3000"
  environment:
    DB_USER: 'admin'
    DB_PASSWD: 'empiredidnothingwrong'

  #volumes:
    #- ./admin:/admin

#volumes:
  #admin: 

 # nginx-proxy:
 #    image: jwilder/nginx-proxy
 #    container_name: nginx-proxy
 #    ports:
 #      - '80:80'
 #      - '443:443'
 #    volumes:
 #      - '/etc/nginx/vhost.d'
 #      - '/usr/share/nginx/html'
 #      - '/etc/nginx/certs:/etc/nginx/certs:ro' 
 #      - '/var/run/docker.sock:/tmp/docker.sock:ro'

 # letsencrypt-nginx-proxy:
 #   container_name: letsencrypt-nginx-proxy
 #   image: 'jrcs/letsencrypt-nginx-proxy-companion'
 #   volumes:
 #     - '/etc/nginx/certs:/etc/nginx/certs'
 #     - '/var/run/docker.sock:/var/run/docker.sock:ro'
 #   volumes_from:
 #     - nginx-proxy

